#!/bin/bash
##
# Hook into git commit event
# Run tests when commiting
##
set -e

# Test PHP syntax for all changed *.php and *.module files
git diff --cached --name-only | while read FILE; do
if [[ "$FILE" =~ ^.+(php|module)$ ]]; then
    # Courtesy of swytsh from the comments below.
    if [[ -f $FILE ]]; then
        php -l "$FILE" 1> /dev/null
        if [ $? -ne 0 ]; then
            echo -e "\e[1;31m\tAborting commit due to files with syntax errors" >&2
            exit 1
        fi
    fi
fi
done

#Run defined defined tests
./run-tests