#!/bin/bash
##
# Run any bash script as a test
##

##
# This script can be called from anywhere so it's good to be relative to project
##
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

##
# Run rspec tests
##
echo "==> Running rspec tests..."
for rspecfile in $DIR/../tests/rspec/*.rb; do
 echo Running $(basename $rspecfile):
 rspec --fail-fast $rspecfile
done

