#!/bin/bash
##
# Run any bash script as a test
##

##
# This script can be called from anywhere so it's good to be relative to project
##
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

if wp core is-installed --quiet &> /dev/null || [ -n "$WP_TEST_URL" ]; then

  ##
  # Run rspec tests
  ##
  echo "==> Running rspec tests..."
  for rspecfile in $DIR/../tests/rspec/*.rb; do
   echo Running $(basename $rspecfile):
   rspec --fail-fast $rspecfile
   if [ $? -ne 0 ]; then
     exit 1
   fi
  done

else
  # Can't figure out rspec tests
  echo "To do rspec testing you need to have Vagrant, WP-cli or set WP_TEST_URL"
  echo "skipping rspec tests..."
  exit 1
fi
